dependencies:
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.3.2
  - rari-capital/solmate@a9e3ea2

autofetch_sources: true

compiler:
  solc:
    version: null
    optimizer:
      enabled: true
      runs: 10000
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts-upgradeable@4.3.2'
      - '@solmate=rari-capital/solmate@a9e3ea2/src'