dependencies:
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.3.2

autofetch_sources: true

compiler:
  solc:
    version: null
    optimizer:
      enabled: false
      runs: 200
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts-upgradeable@4.3.2'