[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.12"


# https://book.getfoundry.sh/reference/config?highlight=fmt#formatter
[fmt]
line_length = 80
number_underscore = "thousands"
