dependencies:
  - Openzeppelin/openzeppelin-contracts@4.4.2
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.3.2

autofetch_sources: true

compiler:
  solc:
    version: 0.8.10
    optimizer:
      enabled: true
      runs: 9999
    remappings:
      - "@openzeppelin=Openzeppelin/openzeppelin-contracts@4.4.2"
      - "@openzeppelin-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.3.2"
